name: Used Car Scout (Discord)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"   # JST 06:00
    - cron: "0 3 * * *"    # JST 12:00
    - cron: "0 9 * * *"    # JST 18:00
    - cron: "0 12 * * *"   # JST 21:00
    - cron: "25 14 * * *"  # JST 23:25

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run hunt
        env:
            DISCORD_WEBHOOK_URL_MAIN: ${{ secrets.DISCORD_WEBHOOK_URL_MAIN }}
            DISCORD_WEBHOOK_URL_MAYBE: ${{ secrets.DISCORD_WEBHOOK_URL_MAYBE }}
          # 任意: 監視対象の上書き（JSON文字列）— 例をSecretsに入れて有効化してください
          # TARGETS_JSON: ${{ secrets.TARGETS_JSON }}
        run: |
          python src/hunt.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.csv
          if-no-files-found: warn
