name: Used Car Scout (Discord)

on:
  workflow_dispatch: {}
  schedule:
    # GitHub Actions の cron は UTC（例: 0 0 → JST 09:00 / 0 12 → JST 21:00）
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run hunt
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # 任意: 監視対象の上書き（JSON文字列）— 例をSecretsに入れて有効化してください
          # TARGETS_JSON: ${{ secrets.TARGETS_JSON }}
        run: |
          python src/hunt.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.csv
          if-no-files-found: warn
